server:
  port: 8080

spring:
  thymeleaf:
    enabled: true
    suffix: .html
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    mode: HTML

logging:
  level:
    root: debug