server:
  port: 9090
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useSSL=false
    username: root
    password: 123456
    hikari:
      connection-test-query: select 1 from dual
      pool-name: Yz-Hikari-Pool