server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store-password: 123456
    key-store: cert.p12

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yz?useSSL=false
    username: root
    password: 123456