server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: select 1 from dual
      connection-timeout: 5000