server:
  port: 8003
spring:
  application:
    name: provider-hystrix-payment
eureka:
  instance:
    instance-id: provider-hystrix-payment8003
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #      defaultZone: http://eureka7001:7001/eureka/
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
