server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  datasource:
    url: jdbc:mysql://localhost:3306/yz?useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.gjt.mm.mysql.Driver